name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: langchain_siliconflow-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        endpoint:
          - "https://api.siliconflow.com/v1"
          - "https://api.siliconflow.cn"
          - default
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Run tests
      if: contains(matrix.endpoint, 'https://api.siliconflow.com')
      env:
        SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_GLOBAL_API_KEY }}
        SILICONFLOW_BASE_URL: ${{ matrix.endpoint }}
      run: uv run pytest
    - name: Run tests
      if: contains(matrix.endpoint, 'https://api.siliconflow.cn')
      env:
        SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_CN_API_KEY }}
        SILICONFLOW_BASE_URL: ${{ matrix.endpoint }}
      run: uv run pytest
    - name: Run tests
      if: matrix.endpoint == 'default'
      env:
        SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_GLOBAL_API_KEY }}
      run: uv run pytest
